name: bloc_resources
description: Utilities for flutter with bloc
version: 0.0.1
author: Icaro R D Temponi
homepage: https://github.com/icarohs7

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  bloc_pattern: ^2.4.2+1
  rxdart: ^0.22.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: