name: bloc_resources
version: 0.0.1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  bloc_pattern: ^2.5.1
  rxdart: ^0.22.6
  core_resources:
    path: ../core_resources
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: