name: bloc_resources
description: Utilities for flutter with bloc
version: 0.0.1
author: Icaro R D Temponi
homepage: https://github.com/icarohs7

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: 2.3.0
  bloc_pattern: ^2.4.4
  rxdart: ^0.22.6
  core_resources:
    path: ../core_resources

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: