name: value_notifier_resources
version: 0.0.1
publish_to: none
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  core_resources:
    git:
      url: https://github.com/icarohs7/unox-flutter-resmodules
      path: core_resources
  flutter:
    sdk: flutter
  functional_listener: ^2.1.0
  rx_notifier:
    git: https://github.com/icarohs7/rx_notifier
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true