name: getx_resources
version: 0.0.1
publish_to: none
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  core_resources:
    git:
      url: https://github.com/icarohs7/unox-flutter-resmodules
      path: core_resources
  flutter:
    sdk: flutter
  get: ^4.6.5
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
