name: modular_mobx_resources
version: 0.0.1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
  flutter_modular: ^1.1.2
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
