name: modular_mobx_resources
version: 0.0.1
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.2
  flutter_modular: 3.3.1
  mobx: ^2.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
