name: core_resources
version: 0.0.1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  async: ^2.4.1
  build_context: ^2.0.4
  dartx: 0.5.0
  dartz: ^0.9.1
  enhanced_future_builder: ^1.0.3
  intl: ^0.16.1
  rxdart: ^0.24.1
  transparent_image: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
dependency_overrides:
  dartx: 0.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
