name: core_resources
version: 0.0.1
publish_to: 'none'
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  build_context: '>=3.0.0'
  dartx: '>=1.1.0'
  flutter:
    sdk: flutter
  flutter_hooks: '>=0.18.0'
  flutter_localizations:
    sdk: flutter
  intl: '>=0.17.0'
dev_dependencies:
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.3.3
  mocktail: ^0.3.0
flutter:
  uses-material-design: true