name: core_resources
version: 0.0.1
publish_to: none
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  async: ^2.8.2
  build_context: ^3.0.0
  dartx: ^1.1.0
  dio: ^4.0.6
  enhanced_future_builder:
    git: https://github.com/icarohs7/enhanced_future_builder
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  http: ^0.13.4
  image: ^3.2.0
  mask_text_input_formatter: ^2.3.0
  mime_type: ^1.0.0
  rxdart: 0.27.4
  transparent_image: ^2.0.0
  url_launcher: ^6.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.3.3
flutter:
