name: core_resources
version: 0.0.1
publish_to: none
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  build_context: ^3.0.0
  collection: ^1.16.0
  dartx: ^1.1.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  functional_listener: ^2.1.0
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  http: ^0.13.5
  http_parser: ^4.0.2
  image: ^3.2.2
  intl: ^0.17.0
  mask_text_input_formatter: ^2.4.0
  mime_type: ^1.0.0
  path: ^1.8.2
  rx_notifier:
    git: https://github.com/icarohs7/rx_notifier
  rxdart: 0.27.4
  transparent_image: ^2.0.0
  url_launcher: ^6.1.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.3.3
  mocktail: ^0.3.0
flutter:
