name: core_resources
version: 0.0.1
publish_to: none
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  build_context: ^3.0.0
  dartx: ^1.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  rxdart: ^0.27.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.3.3
  mocktail: ^0.3.0
  path: ^1.8.2
  path_provider: ^2.0.12
  path_provider_platform_interface: ^2.0.5
  plugin_platform_interface: ^2.1.3
flutter:
