name: core_resources
version: 0.0.1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  async: ^2.4.2
  build_context: ^2.0.4
  dartx: 0.5.0
  freezed_annotation: ^0.12.0
  enhanced_future_builder: ^1.0.3
  rxdart: ^0.25.0
  transparent_image: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
