name: core_resources
version: 0.0.1
publish_to: none
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  async: ^2.6.1
  build_context: ^3.0.0
  dartx: ^1.0.0
  enhanced_future_builder:
    git: https://github.com/icarohs7/enhanced_future_builder
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  transparent_image: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
