name: core_resources
version: 0.0.1
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  async: ^2.5.0
  build_context: ^3.0.0
  dartx: ^0.6.0
  enhanced_future_builder:
    git: https://github.com/icarohs7/enhanced_future_builder
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.14.0
  rxdart: ^0.26.0
  transparent_image: ^2.0.0-nullsafety.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
