name: core_resources
version: 0.0.1
publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  build_context:
    git:
      url: https://github.com/icarohs7/build_context
  dartx: '>=1.1.0'
  equatable: '>=2.0.5'
  flutter:
    sdk: flutter
  flutter_hooks: '>=0.18.0'
  flutter_localizations:
    sdk: flutter
  intl: '>=0.17.0'
  logging: '>=1.3.0'
dev_dependencies:
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.3.3
  mocktail: ^1.0.0
flutter:
  uses-material-design: true