name: core_resources
version: 0.0.1
environment:
  sdk: ">=2.6.0-dev.4.0.flutter-1103600280 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  shimmer: ^1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
