name: core_resources
version: 0.0.1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  async: ^2.4.0
  dartx: ^0.2.0
  intl: ^0.16.1
  rxdart: ^0.23.1
  shimmer: ^1.0.1
  transparent_image: ^1.0.0
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
