name: core_resources
version: 0.0.1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  async: ^2.4.1
  dartx: 0.4.1
  intl: ^0.16.1
  rxdart: ^0.24.0
  transparent_image: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
dependency_overrides:
  dartx: 0.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
