name: abstract_db_resources
version: 0.0.1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  core_resources:
    path: ../core_resources
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
