name: maskedinput_resources
version: 0.0.1
environment:
  sdk: ">=2.6.1 <3.0.0"
dependencies:
  mask_text_input_formatter: ^1.0.5
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: