name: basic_resource_pack
version: 0.0.1
environment:
  sdk: ">=2.6.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  bloc_resources:
    path: ../bloc_resources
  navigation_resources:
    path: ../navigation_resources
  rest_resources:
    path: ../rest_resources
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: