name: search_resources
version: 0.0.1
publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  core_resources:
    git:
      url: https://github.com/icarohs7/unox-flutter-resmodules
      path: core_resources
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true