name: navigation_resources
version: 0.0.1
environment:
  sdk: ">=2.6.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  core_resources:
    path: ../core_resources
  fluro: ^1.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: