library core_resources;

export 'package:build_context/build_context.dart';
export 'package:dartx/dartx.dart' hide Function0, Function1, Function2, Function3, Function4;
export 'package:dio/dio.dart';
export 'package:flutter_hooks/flutter_hooks.dart';
export 'package:flutter_localizations/flutter_localizations.dart';
export 'package:hive_flutter/hive_flutter.dart';
export 'package:html_unescape/html_unescape.dart';
export 'package:rxdart/rxdart.dart' hide Rx;

export 'src/baseclasses/base_api_service.dart';
export 'src/baseclasses/base_router.dart';
export 'src/classes/core_router_observer.dart';
export 'src/core.dart';
export 'src/database/base_repository.dart';
export 'src/database/hive_database.dart' hide HiveDatabase, HiveBoxAdapter;
export 'src/database/t_database.dart' hide JsonObject;
export 'src/extensions/async_snapshot_extensions.dart';
export 'src/extensions/color_extensions.dart';
export 'src/extensions/context_extensions.dart';
export 'src/extensions/dio_extensions.dart';
export 'src/extensions/execution_extensions.dart';
export 'src/extensions/future_extensions.dart';
export 'src/extensions/number_extensions.dart';
export 'src/extensions/object_extensions.dart';
export 'src/extensions/stream_extensions.dart';
export 'src/extensions/string_extensions.dart';
export 'src/extensions/time_extensions.dart';
export 'src/models/tuple.dart';
export 'src/utils/common_intents.dart';
export 'src/utils/date_time.dart';
export 'src/utils/dio.dart';
export 'src/utils/fade_page_route.dart';
export 'src/utils/form_validation.dart';
export 'src/utils/hooks.dart';
export 'src/utils/json.dart';
export 'src/utils/log.dart';
export 'src/utils/math.dart';
export 'src/utils/nav.dart';
export 'src/utils/simple_search_delegate.dart';
export 'src/utils/ui.dart';
export 'src/utils/utils.dart';
export 'src/widgets/auto_complete_text_view.dart';
export 'src/widgets/conditional_render.dart';
export 'src/widgets/dialogs.dart';
export 'src/widgets/dismissible_and_editable_slidable.dart';
export 'src/widgets/dismissible_from_end_to_start.dart';
export 'src/widgets/editable_label.dart';
export 'src/widgets/loading_button.dart';
export 'src/widgets/number_stepper.dart';
export 'src/widgets/password_form_field.dart';
export 'src/widgets/refresh_action_button.dart';
export 'src/widgets/splash_widget.dart';
export 'src/widgets/transitions.dart';
