name: domaindefinition_resources
version: 0.0.1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  shared_preferences: ^0.5.4+3
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
