name: firestore_db_resources
version: 0.0.1
publish_to: none
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  abstract_stringkey_db_resources:
    git:
      url: https://github.com/icarohs7/unox-flutter-resmodules
      path: abstract_stringkey_db_resources
  cloud_firestore: ^3.1.14
  flutter:
    sdk: flutter
dev_dependencies:
  fake_cloud_firestore: ^1.2.2
  flutter_test:
    sdk: flutter
flutter:
