name: hive_db_resources
version: 0.0.1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  abstract_db_resources:
    path: ../abstract_db_resources
  flutter:
    sdk: flutter
dependency_overrides:
  dartx: 0.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
