name: hive_db_resources
version: 0.0.1
publish_to: none
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  abstract_db_resources:
    git:
      url: https://github.com/icarohs7/unox-flutter-resmodules
      path: abstract_db_resources
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  rxdart: ^0.27.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
