name: hive_db_resources
version: 0.0.1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  abstract_db_resources:
    path: ../abstract_db_resources
  flutter:
    sdk: flutter
dev_dependencies:
  build_resolvers: ^1.3.11
  flutter_test:
    sdk: flutter
flutter:
