name: hive_db_resources
version: 0.0.1
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  abstract_db_resources:
    path: ../abstract_db_resources
  flutter:
    sdk: flutter
  hive: ^1.6.0-nullsafety.2
  hive_flutter: ^1.0.0-nullsafety.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
