name: getx_core_resources
description: Monolithic library with opinionated state, dependency injection and storage utilities
publish_to: none
version: 0.0.1
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  core_resources:
    git:
      url: https://github.com/icarohs7/unox-flutter-resmodules
      path: core_resources
  flutter:
    sdk: flutter
  get: ^4.6.5
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
