name: getx_core_resources
description: Monolithic library with opinionated state, dependency injection and storage utilities
publish_to: none
version: 0.0.1
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  abstract_db_resources:
    path: ../abstract_db_resources
  core_resources:
    path: ../core_resources
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_html:
    git:
      ref: db41f465a7ecf75e173c4507e127aea1327bc4f6
      url: https://github.com/Sub6Resources/flutter_html
  get: ^4.6.1
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  http: ^0.13.3
  image: ^3.1.3
  mime_type: ^1.0.0
  rxdart: ^0.27.2
  url_launcher: 6.0.10
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
