name: getx_core_resources
description: Monolithic library with opinionated state, dependency injection and storage utilities
publish_to: none
version: 0.0.1
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  abstract_db_resources:
    git:
      url: https://github.com/icarohs7/unox-flutter-resmodules
      path: abstract_db_resources
  dio: ^4.0.6
  flutter:
    sdk: flutter
  get: ^4.6.5
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  http: ^0.13.4
  image: ^3.2.0
  mime_type: ^1.0.0
  rxdart: 0.27.3
  url_launcher: ^6.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
