name: reactor_fp_resources
version: 0.0.1
publish_to: 'none'
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  core_resources:
    git:
      url: https://github.com/icarohs7/unox-flutter-resmodules
      path: core_resources
  flutter:
    sdk: flutter
  fpdart:
    git:
      ref: b7e87e271b43caf05339100e2ab7f205579d346b
      url: https://github.com/SandroMaglione/fpdart
  value_notifier_resources:
    git:
      url: https://github.com/icarohs7/unox-flutter-resmodules
      path: value_notifier_resources
dev_dependencies:
  equatable: ^2.0.5
  flutter_test:
    sdk: flutter
  rxdart: ^0.27.7
flutter:
  uses-material-design: true